name: Deploy to Surge.sh

on:
  push:
    branches:
      - main  # Se ejecutará cada vez que haya un push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Surge
        run: npm install -g surge

      - name: Desplegar a Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: surge ./ --domain PrimerParcial-Electivall.surge.sh --token $SURGE_TOKEN
